// This file would be generated by the FlutterFire CLI
// For this example, we'll create a placeholder
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // In a real app, you would have platform-specific Firebase options here
    // This is just a placeholder - you'll need to replace this with your actual Firebase config
    return const FirebaseOptions(
      apiKey: "AIzaSyAeAlAaTqZdbdxh3YcYxWi_iK-ZPft5rP4",
      appId: "1:478026757778:web:e6450f4f783edfe190184b",
      messagingSenderId: "478026757778",
      projectId: "ubia-3fa09",
      authDomain: "ubia-3fa09.firebaseapp.com",
      storageBucket: "ubia-3fa09.firebasestorage.app",
      measurementId: "G-4RC5QCQQJK"
    );
  }
}

